### ISSUE TITLE
[Question|Feature] Different Options for testing.

### ISSUE THREAD

**Issue by Lexanius** [mreuvers/typescript-logging#27]
Hi,

this is a very nice tool. I like it. 
After using i have a question, is it possible to define different LoggerFactoryOptions for testing?
E.g. for testing Trace and normal Debug?

Richard

**Comment by mreuvers** [comment]
Hello @Lexanius 

Thank you! :)

I am not sure if I understand your question correctly, but I think you mean you want to run the same code when testing, in trace and otherwise in say debug?

I don't know what kind of environment you're using but let's assume you run tests with node here.

You could for example pass in an environment variable when running the tests, e.g:

In your package.json, in the test I specified the LOGLEVEL variable and then run the tests (here jasmine as example but could be mocha or anything else).

```
"scripts": {
   "test": "LOGLEVEL=test jasmine-node --verbose ./dist-test/spec",
}
```

Now at the place you are currently creating a LoggerFactoryOptions instance - let's say you do that somewhere centrally in a function, you could test for it in TypeScript and set the appropriate level.

```
export function createLoggerFactoryOptions(): LoggerFactoryOptions {
  let level: LogLevel = LogLevel.Debug;
  if  (process && process.env && process.env.LOGLEVEL === "test") {
    level = LogLevel.Trace;
    console.log("LOGLEVEL=" + process.env.LOGLEVEL);
  }
  const options = new LoggerFactoryOptions();
  options.addLogGroupRule(new LogGroupRule(new RegExp(".+"), level));
  return options;
}
```
On command-line: npm run test 

Will now set the environment variable to 'test', which then assures in the function above that your logging will be on trace instead.

Please note that this example works for a 'unixy' os, for example windows uses a set var=xxx syntax, you may want to use the cross-env package instead to make sure it works everywhere.

I hope this answers your question.
`

**Comment by Lexanius** [comment]
Yeah cool. i will test it.

Thank you.

**Comment by mreuvers** [comment]
Hey hey, did you manage to do it?

**Comment by Lexanius** [comment]
Yeah i managed to do it, but not with cross-env. Because i use angular, so the environment is easy to use: `    "test": "ng test --env test",`

```
import { environment } from './environments/environment';

export function createLoggerFactoryOptions(): LoggerFactoryOptions {
    let level: LogLevel = LogLevel.Debug;
    if (environment && typeof environment.LOGLEVEL === 'string') {
        switch (environment.LOGLEVEL.toLowerCase()) {
            case 'trace':
                level = LogLevel.Trace;
                break;
            case 'debug':
                level = LogLevel.Debug;
                break;
            case 'info':
                level = LogLevel.Info;
                break;
            case 'warn':
                level = LogLevel.Warn;
                break;
            case 'error':
                level = LogLevel.Error;
                break;
            case 'fatal':
                level = LogLevel.Fatal;
                break;
        }
    }
    return new LoggerFactoryOptions()
        .addLogGroupRule(new LogGroupRule(new RegExp('.+'), level));
}
```
