### ISSUE TITLE
Angular10

### ISSUE THREAD

**Issue by dibog** [mreuvers/typescript-logging#54]
Hi,

I like the similiarity with slf4j/log4j. After upgrading to Angular10 I got those warnings with regards to the logging framework:

<code>
WARNING in D:\git\ZeroEngineering\skill-tree-ide\src\environments\log.config.ts depends on 'typescript-logging'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
</code>

**Comment by mreuvers** [comment]
Hey there,

Apologies for the delay. This warning is indeed because it currently only ships as commonjs modules. In the future this will be changed. 

If you're feeling lucky you could build the current master and link to it from your own project, then build your own project again. Do the warnings disappear in that case?

Do you have a simple quickstart which shows the warning? Then I can verify it later in the future that it works before releasing.

**Comment by dibog** [comment]
Hi again,

sorry for being so late with a response. Unfortunatly I can't share our code. But here is a copy of the error message:

WARNING in \some\path\src\lib\log.config.ts depends on 'typescript-logging'. CommonJS or AMD dependencies c
an cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

**Comment by mreuvers** [comment]
No problem and thank you. The current version is going to be finalized soon (becoming a 1.0.0).

After that a major rewrite will happen for the next major version. That should make this warning go away as well as it will be shipped with ems modules then.

**Comment by mreuvers** [comment]
Closing this issue as it's old, typescript logging 2 (major new version) has been released. Consider upgrading.

The new release bundles both esm or commonjs (so it's a bundler's choice then).
